server:
  port: 3000

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0